create table if not exists public.sns_follower_records (
  id bigint generated by default as identity primary key,
  platform text not null,
  record_date date not null,
  follower_count integer,
  source text not null default 'github_actions',
  status text not null default 'success',
  error_message text,
  created_at timestamptz not null default now(),
  unique (platform, record_date, status)
);

create index if not exists sns_follower_records_record_date_idx
  on public.sns_follower_records (record_date desc);

create index if not exists sns_follower_records_platform_idx
  on public.sns_follower_records (platform);

alter table public.sns_follower_records enable row level security;

drop policy if exists "sns follower records are publicly readable" on public.sns_follower_records;
create policy "sns follower records are publicly readable"
  on public.sns_follower_records
  for select
  using (true);

grant select on table public.sns_follower_records to anon, authenticated;
grant select, insert, update on table public.sns_follower_records to service_role;
grant usage, select on all sequences in schema public to service_role;
